// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEsEmjrusIKWvmqTLLHY70SGMzICzr2Cg',
    appId: '1:519432996127:web:51cc47957245215ad69c2a',
    messagingSenderId: '519432996127',
    projectId: 'parking-coordinator',
    authDomain: 'parking-coordinator.firebaseapp.com',
    storageBucket: 'parking-coordinator.appspot.com',
    measurementId: 'G-D2DVK7NDQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc61C1LHmQmJLH7sAH80T4q7DdihzR4gM',
    appId: '1:519432996127:android:0d7f83290976baabd69c2a',
    messagingSenderId: '519432996127',
    projectId: 'parking-coordinator',
    storageBucket: 'parking-coordinator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2JdiWE3U2x7z6GWcMmH9xCqgrdjZlaJk',
    appId: '1:519432996127:ios:8783508f0e4029aad69c2a',
    messagingSenderId: '519432996127',
    projectId: 'parking-coordinator',
    storageBucket: 'parking-coordinator.appspot.com',
    iosClientId: '519432996127-3hi81euabhautqjqusq8pnm59ntfq7an.apps.googleusercontent.com',
    iosBundleId: 'com.edanlevy.parkingCoordinator',
  );
}
